server:
    port: 8082
#spring:
#    application:
#        name:mango-backup
# backup datasource
mango:
    backup:
        datasource:
            host: localhost
            userName: root
            password: 123456
            database: mango
